name: 🚀 Docker Build Check (CI)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-containers:
    name: Compilar Imágenes Docker en la Nube
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout del código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso Backend: Cambiamos context a la raíz (.) y apuntamos al archivo específico
      - name: 📦 Compilar Docker Imagen Backend (FastAPI)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: false
          tags: biomedical-rag-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Paso Frontend: Cambiamos context a la raíz (.) y apuntamos al archivo específico
      - name: 📦 Compilar Docker Imagen Frontend (Streamlit)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: false
          tags: biomedical-rag-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
